#ProjectileKnockback 配置文件

#非玩家发射的投掷物(如发射器)也可击退玩家
kbOnNonPlayer: true

#启用钓鱼竿
kbOnFishingRod: true

#启用末影珍珠
kbOnEnderPearl: true

#启用雪球
kbOnSnowball: true

#启用鸡蛋
kbOnEgg: true

#横向击退惯性(默认1)
horizontalVelocity: 1

#纵向击退惯性(默认1)
verticalVelocity: 1